kind: pipeline
type: docker
name: greeting

environment:
  GREETING_EN: hello

steps:
- name: en
  image: alpine
  commands:
  - echo $GREETING_EN
  - echo world
- name: test
  image: node
  commands:
  - npm install